version: '3.8'
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banque_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/update_v1.sql:/docker-entrypoint-initdb.d/update_v1.sql
    networks:
      - app_network

  app:
    build: ./tp1jdbc/
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/banque_db
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
